name: Generate Pacman Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Pacman
        uses: Platane/pacman@v1
        with:
          github_user_name: tenoriobn
          outputs: |
            dist/pacman.svg
            dist/pacman-dark.svg?palette=github-dark

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output
          folder: dist
